apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ulys
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - canary.yaml
  - networkpolicy.yaml
  - authorization.yaml
images:
  - name: worker
    newName: us-central1-docker.pkg.dev/ulys-dev-PROJECT_ID/ulys/worker
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
